Выполнил все таски :)
js-tasks-ru/jsbasic-20221114_dima-lavrisiuk pull request #2
Opened 2022-11-21 23:32 UTC by DmitriyLavrisiuk

1 таск делал не через рекурсию, подумал цикл будет более практичнее.

2022-11-21 23:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-22 12:28 UTC, SinimaWath requested changes

2022-11-22 12:28 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if(!str.length) {
Стоит упростить до: `if (!str)`

2022-11-22 12:33 UTC, DmitriyLavrisiuk commented on 1-module/3-task/index.js
> +  if(!str.length) {
Сделал

2022-11-22 12:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-11-23 11:35 UTC, SinimaWath approved these changes

2022-11-23 11:35 UTC, merged